- name: install nginx server
  ansible.builtin.package:
    name: "{{ web_server_package }}"
    state: present

- name: start service
  ansible.builtin.service:
    name: "{{ web_service_name }}"
    state: started
    enabled: true

- name: import task from common role #this will use common folder 
  ansible.builtin.import_role: 
    name: common
    tasks_from: app-pre-req

- name: Import frontend service task
  import_tasks: config_file.yaml    #this is also a task but for usage practice i create separte file for this task called template.yaml
